services:
  - type: web
    name: wazuh-attack-correlator
    runtime: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: cd /opt/render/project/src && python -c "from correlation_tool.server import run_server; run_server()"
    plan: free
    healthCheckPath: /healthz
    healthCheckInterval: 30
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: WAZUH_HOST
        value: https://172.16.20.62:55000
      - key: WAZUH_INDEXER_HOST
        value: https://172.16.20.62:9200
      - key: WAZUH_USER
        value: admin
      - key: WAZUH_PASSWORD
        value: l6ArtMq7XC*XGtK08mwGBCPsWXh?Lgxv
      - key: WAZUH_VERIFY_SSL
        value: "false"
